"""empty message

Revision ID: 8b04cdba7ca0
Revises: f4f7856d89b6
Create Date: 2022-12-02 11:14:22.170094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b04cdba7ca0'
down_revision = 'f4f7856d89b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revision_pji',
    sa.Column('no_group', sa.String(length=120), nullable=False),
    sa.Column('no', sa.String(length=120), nullable=False),
    sa.Column('group', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('computed_tomography_number', sa.String(length=30), nullable=False),
    sa.Column('csn', sa.String(length=30), nullable=True),
    sa.Column('PJI_revision_date', sa.String(length=30), nullable=True),
    sa.Column('Date_of_first_surgery', sa.String(length=30), nullable=True),
    sa.Column('Date_of_last_surgery', sa.String(length=30), nullable=True),
    sa.Column('primary_revision_native_hip', sa.String(length=30), nullable=True),
    sa.Column('acute_chronic', sa.String(length=30), nullable=True),
    sa.Column('asa', sa.String(length=30), nullable=True),
    sa.Column('laterality', sa.String(length=30), nullable=True),
    sa.Column('joint', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('age', sa.String(length=30), nullable=True),
    sa.Column('height', sa.String(length=30), nullable=True),
    sa.Column('weight', sa.String(length=30), nullable=True),
    sa.Column('bmi', sa.String(length=30), nullable=True),
    sa.Column('serum_ESR', sa.String(length=30), nullable=True),
    sa.Column('serum_WBC', sa.String(length=30), nullable=True),
    sa.Column('segment', sa.String(length=30), nullable=True),
    sa.Column('hgb', sa.String(length=30), nullable=True),
    sa.Column('platelet', sa.String(length=30), nullable=True),
    sa.Column('p_t', sa.String(length=30), nullable=True),
    sa.Column('aptt', sa.String(length=30), nullable=True),
    sa.Column('fibrinogen', sa.String(length=30), nullable=True),
    sa.Column('d_dimer', sa.String(length=30), nullable=True),
    sa.Column('Serum_CRP', sa.String(length=30), nullable=True),
    sa.Column('cr', sa.String(length=30), nullable=True),
    sa.Column('ast', sa.String(length=30), nullable=True),
    sa.Column('alt', sa.String(length=30), nullable=True),
    sa.Column('positive_histology', sa.String(length=30), nullable=True),
    sa.Column('synovial_WBC', sa.String(length=30), nullable=True),
    sa.Column('synovial_Neutrophil', sa.String(length=30), nullable=True),
    sa.Column('turbidity', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('lymphocyte', sa.String(length=30), nullable=True),
    sa.Column('monocyte', sa.String(length=30), nullable=True),
    sa.Column('eosinophil', sa.String(length=30), nullable=True),
    sa.Column('synovial_leukocyte_esterase', sa.String(length=30), nullable=True),
    sa.Column('total_core', sa.String(length=30), nullable=True),
    sa.Column('icm_2', sa.String(length=30), nullable=True),
    sa.Column('minor_icm_criteria_total', sa.String(length=30), nullable=True),
    sa.Column('icm_1', sa.String(length=30), nullable=True),
    sa.Column('minor_msis_criteria_total', sa.String(length=30), nullable=True),
    sa.Column('msis_final_classification', sa.String(length=30), nullable=True),
    sa.Column('positive_culture', sa.String(length=30), nullable=True),
    sa.Column('sinus_tract', sa.String(length=30), nullable=True),
    sa.Column('pulurence', sa.String(length=30), nullable=True),
    sa.Column('single_positive_culture', sa.String(length=30), nullable=True),
    sa.Column('total_cci', sa.String(length=30), nullable=True),
    sa.Column('congestive_heart_failure', sa.String(length=30), nullable=True),
    sa.Column('cardiac_arrhythmia', sa.String(length=30), nullable=True),
    sa.Column('valvular_disease', sa.String(length=30), nullable=True),
    sa.Column('pulmonary_circulation_disorders', sa.String(length=30), nullable=True),
    sa.Column('peripheral_vascular_disorders', sa.String(length=30), nullable=True),
    sa.Column('hypertension_uncomplicated', sa.String(length=30), nullable=True),
    sa.Column('hypertension_complicated', sa.String(length=30), nullable=True),
    sa.Column('paralysis', sa.String(length=30), nullable=True),
    sa.Column('other_neurological_disorders', sa.String(length=30), nullable=True),
    sa.Column('chronic_pulmonary_disease', sa.String(length=30), nullable=True),
    sa.Column('diabetes_uncomplicated', sa.String(length=30), nullable=True),
    sa.Column('hypothyroidism', sa.String(length=30), nullable=True),
    sa.Column('renal_failure', sa.String(length=30), nullable=True),
    sa.Column('liver_disease', sa.String(length=30), nullable=True),
    sa.Column('peptic_ulcer_disease_excluding_bleeding', sa.String(length=30), nullable=True),
    sa.Column('aids_hiv', sa.String(length=30), nullable=True),
    sa.Column('lymphoma', sa.String(length=30), nullable=True),
    sa.Column('metastatic_cancer', sa.String(length=30), nullable=True),
    sa.Column('solid_tumor_without_metastasis', sa.String(length=30), nullable=True),
    sa.Column('rheumatoid_arthritis_collagen', sa.String(length=30), nullable=True),
    sa.Column('coagulopathy', sa.String(length=30), nullable=True),
    sa.Column('obesity', sa.String(length=30), nullable=True),
    sa.Column('weight_loss', sa.String(length=30), nullable=True),
    sa.Column('fluid_electrolyte_disorders', sa.String(length=30), nullable=True),
    sa.Column('blood_loss_anemia', sa.String(length=30), nullable=True),
    sa.Column('deficiency_anemia', sa.String(length=30), nullable=True),
    sa.Column('alcohol_abuse', sa.String(length=30), nullable=True),
    sa.Column('drug_abuse', sa.String(length=30), nullable=True),
    sa.Column('psychoses', sa.String(length=30), nullable=True),
    sa.Column('depression', sa.String(length=30), nullable=True),
    sa.Column('total_elixhauser_groups_per_record', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('no_group'),
    sa.UniqueConstraint('computed_tomography_number'),
    sa.UniqueConstraint('csn'),
    sa.UniqueConstraint('group'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('no'),
    sa.UniqueConstraint('no_group')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revision_pji')
    # ### end Alembic commands ###
